# Generated by Django 5.1 on 2024-08-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_livro_capa"),
    ]

    operations = [
        migrations.AddField(
            model_name="editora",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
